version: '3.9'
services:
  database:
    build: ./database/
    ports:
      - '5432:5432'
    volumes:
      - ~/volumes/your_service_name:/var/lib/postgresql/data
    # can use env_vars https://docs.docker.com/compose/environment-variables/, ${POSTGRES_PASSWORD}
    environment:
      - POSTGRES_PASSWORD=PASSWORD

    # or use a dot env file
    # env_file:
    #   - .env

